# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-21 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default=0, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pub_date_created',
        ),
        migrations.AddField(
            model_name='image',
            name='Image_comments',
            field=models.CharField(blank=True, default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.CharField(blank=True, default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=40),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.CharField(blank=True, default=0, max_length=40),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.CharField(blank=True, default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
