# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-22 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Emma',
        ),
    ]
